# Generated by Django 5.1.2 on 2025-01-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_community_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='community_profiles/'),
        ),
    ]
