# Generated by Django 5.0.7 on 2024-11-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={},
        ),
        migrations.AlterModelOptions(
            name='list',
            options={},
        ),
        migrations.RemoveField(
            model_name='board',
            name='created',
        ),
        migrations.RemoveField(
            model_name='board',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='label',
            name='created',
        ),
        migrations.RemoveField(
            model_name='label',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='list',
            name='created',
        ),
        migrations.RemoveField(
            model_name='list',
            name='modified',
        ),
        migrations.AddField(
            model_name='board',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='board',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='label',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='label',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='list',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='list',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
