# Generated by Django 5.0.7 on 2024-11-21 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_board_options_alter_label_options_and_more'),
        ('members', '0008_alter_member_options_remove_member_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='label_modified', to='members.member'),
        ),
    ]
