# Generated by Django 5.1.4 on 2025-01-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HabitTracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='section',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Night', 'Night'), ('Others', 'Others')], default='Others', max_length=20),
        ),
        migrations.AddField(
            model_name='habit',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
