# Generated by Django 5.0.7 on 2024-12-04 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HabitTracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='is_reset',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='start_date',
        ),
        migrations.AddField(
            model_name='habit',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='goal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='habit',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='habit',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to='HabitTracker.habit')),
            ],
        ),
    ]
