# Generated by Django 5.0.7 on 2024-12-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HabitTracker', '0002_remove_habit_end_date_remove_habit_is_reset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
