# Generated by Django 5.1.2 on 2025-01-23 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HabitTracker', '0003_habit_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyprogress',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='start_date',
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='completed_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='habit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='duration',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='habit',
            name='goal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='habit',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL),
        ),
    ]
