# Generated by Django 5.0.7 on 2024-11-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_usertoken_delete_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
