# Generated by Django 5.0.7 on 2024-11-10 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_usertoken_expired'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
