# Generated by Django 5.0.7 on 2024-11-10 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_rename_user_id_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='user_id',
        ),
    ]
